/**
 * Centralized Application Constants
 */

export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '/api/v1';

export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'erp_access_token',
  REFRESH_TOKEN: 'erp_refresh_token',
  USER_INFO: 'erp_user_info',
  SIDEBAR_COLLAPSED: 'erp_sidebar_collapsed',
};

export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  USER: 'USER',
};

export const PERMISSIONS = {
  // USER
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_VIEW: 'USER_VIEW',

  // CATEGORY
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  CATEGORY_VIEW: 'CATEGORY_VIEW',

  // UNIT
  UNIT_CREATE: 'UNIT_CREATE',
  UNIT_UPDATE: 'UNIT_UPDATE',
  UNIT_DELETE: 'UNIT_DELETE',
  UNIT_VIEW: 'UNIT_VIEW',

  // WAREHOUSE
  WAREHOUSE_CREATE: 'WAREHOUSE_CREATE',
  WAREHOUSE_UPDATE: 'WAREHOUSE_UPDATE',
  WAREHOUSE_DELETE: 'WAREHOUSE_DELETE',
  WAREHOUSE_VIEW: 'WAREHOUSE_VIEW',

  // PRODUCT
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  PRODUCT_VIEW: 'PRODUCT_VIEW',

  // STOCK
  STOCK_IMPORT: 'STOCK_IMPORT',
  STOCK_EXPORT: 'STOCK_EXPORT',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  STOCK_VIEW: 'STOCK_VIEW',
  STOCK_UPDATE: 'STOCK_UPDATE',

  // SUPPLIER
  SUPPLIER_CREATE: 'SUPPLIER_CREATE',
  SUPPLIER_UPDATE: 'SUPPLIER_UPDATE',
  SUPPLIER_VIEW: 'SUPPLIER_VIEW',

  // PURCHASE ORDER
  PURCHASE_CREATE: 'PURCHASE_CREATE',
  PURCHASE_UPDATE: 'PURCHASE_UPDATE',
  PURCHASE_APPROVE: 'PURCHASE_APPROVE',
  PURCHASE_CANCEL: 'PURCHASE_CANCEL',

  // GOODS RECEIPT
  GOODS_RECEIPT_CREATE: 'GOODS_RECEIPT_CREATE',
  GOODS_RECEIPT_VIEW: 'GOODS_RECEIPT_VIEW',
  GOODS_RECEIPT_IMPORT: 'GOODS_RECEIPT_IMPORT',

  // CUSTOMER
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
  CUSTOMER_VIEW: 'CUSTOMER_VIEW',

  // SALES ORDER
  SALES_CREATE: 'SALES_CREATE',
  SALES_UPDATE: 'SALES_UPDATE',
  SALES_APPROVE: 'SALES_APPROVE',
  SALES_VIEW: 'SALES_VIEW',
  SALES_CANCEL: 'SALES_CANCEL',

  // DELIVERY
  DELIVERY_CREATE: 'DELIVERY_CREATE',
  DELIVERY_VIEW: 'DELIVERY_VIEW',
  DELIVERY_EXPORT: 'DELIVERY_EXPORT',

  // REPORT
  REPORT_VIEW: 'REPORT_VIEW',
};

// Map predefined roles to their permissions based on DataInitializer.java
export const ROLE_PERMISSIONS = {
  [ROLES.USER]: [
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.UNIT_VIEW,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.STOCK_VIEW,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.UNIT_CREATE,
    PERMISSIONS.UNIT_UPDATE,
    PERMISSIONS.UNIT_VIEW,
    PERMISSIONS.WAREHOUSE_CREATE,
    PERMISSIONS.WAREHOUSE_UPDATE,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.STOCK_IMPORT,
    PERMISSIONS.STOCK_EXPORT,
    PERMISSIONS.STOCK_TRANSFER,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_UPDATE,
    PERMISSIONS.REPORT_VIEW,
  ],
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
};
